services:
  mysql:
    container_name: mysql
    build: backend/db
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: Daytel$4125
      MYSQL_DATABASE: mydb
      MYSQL_USER: email
      MYSQL_PASSWORD: password

    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 15s
      retries: 10

  backend:
    build: backend/server
    container_name: backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8000:8000"
    volumes:
      - ./backend/db:/db
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: email
      DB_PASSWORD: password
      DB_NAME: mydb
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000

  frontend:
    build: frontend
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "8080:80"
    volumes:
      - frontend_dist:/usr/share/nginx/html

  nginx:
    image: nginx:latest
    container_name: nginx
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./frontend/nginx.conf/default.conf:/etc/nginx/conf.d/default.conf
      - frontend_dist:/usr/share/nginx/html
      - ./ssl/certs/nginx-selfsigned.crt:/etc/ssl/certs/nginx-selfsigned.crt
      - ./ssl/private/nginx-selfsigned.key:/etc/ssl/private/nginx-selfsigned.key
    restart: unless-stopped
    command: /bin/sh -c 'echo "Frontend доступен по адресу -> http://localhost:8080" && nginx -g "daemon off;"'

volumes:
  mysql_data:
  frontend_dist: